
CREATE TABLE HR.ARTIST_DIM
(
  ARTIST_PK  NUMBER PRIMARY KEY,
  ID         VARCHAR2(255),
  NAME       VARCHAR2(255),
  LOCATION   VARCHAR2(255)
);

CREATE TABLE HR.DATE_DIM
(
  DATE_PK          NUMBER PRIMARY KEY,
  TS               NUMBER,
  YEAR             NUMBER,
  QUARTER          NUMBER,
  MONTH            NUMBER,
  WEEKOFMONTH      NUMBER,
  WEEKOFYEAR       NUMBER,
  MONTHNAME        VARCHAR2(255),
  DAYOFYEAR        NUMBER,
  WEEKDAYNAME      VARCHAR2(255),
  DAY              NUMBER,
  QUARTERNAME      VARCHAR2(255),
  MONTHNAME_SHORT  VARCHAR2(255),
  DAYOFWEEK        NUMBER,
  HOUR             VARCHAR2(255),
  MINUTE           NUMBER
);


CREATE TABLE HR.SONG_DIM
(
  SONG_PK          NUMBER PRIMARY KEY,
  ID               VARCHAR2(255),
  TITLE            VARCHAR2(255),
  "Duration(min)"  NUMBER,
  YEAR             NUMBER
);


CREATE TABLE HR.USERS_DIM
(
  USER_PK   NUMBER PRIMARY KEY,
  ID        VARCHAR2(255),
  NAME      VARCHAR2(255),
  LOCATION  VARCHAR2(255),
  GENDER    VARCHAR2(255)
);



CREATE TABLE HR.SONGPLAY_FACT (
    DATE_FK NUMBER REFERENCES HR.DATE_DIM(DATE_PK),
    USER_FK NUMBER REFERENCES HR.USERS_DIM(USER_PK),
    SONG_FK NUMBER REFERENCES HR.SONG_DIM(SONG_PK),
    ARTIST_FK NUMBER REFERENCES HR.ARTIST_DIM(ARTIST_PK),
    SESSIONID_DD NUMBER,
    LEVEL_DD VARCHAR2(255)
);
